name: build
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

env:
  GO_VERSION: stable

jobs:

  build:
    name: Build Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [semantic, concurrency]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: ${{ matrix.module }}/go.sum
          check-latest: false

      - name: go build
        working-directory: ${{ matrix.module }}
        run: |
          go build ./...
        env:
          GOPATH: /home/runner/work/${{ github.event.repository.name }}/go