name: build
on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [semantic, concurrency]

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache: true
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: go build
        working-directory: ${{ matrix.module }}
        run: |
          go build ./...