name: test coverage coverallsapp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read # чтоб бейджи грузились

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.out
          format: golang
