name: test coverage
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'semantic/**'
      - 'concurrency/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write # чтоб бейджи грузились
#  pull-requests: write  

env:
  GO_VERSION: stable

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        module: [semantic, concurrency]
    defaults:
      run:
        working-directory: ${{ matrix.module }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache: true
          cache-dependency-path: ${{ matrix.module }}/go.sum
          #go-version: ${{ env.GO_VERSION }}
          #cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: |
          go test ./... -race -covermode=atomic -coverprofile=coverage_package_${{ matrix.module }}.out
          pwd
          ls

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.module }}
          path: ${{ matrix.module }}/coverage_package_${{ matrix.module }}.out

      - name: Upload to Coveralls (flag = module)
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file:  ${{ matrix.module }}/coverage_package_${{ matrix.module }}.out
          format: golang  
          flag-name: ${{ matrix.module }}
          parallel: true

  Finish:
    needs: Test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Finish upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          #coveralls-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel-finished: true
          carryforward: "semantic,concurrency"

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage-files

      - name: Generate coverage badge JSONs
        run: |
          set -euo pipefail
          mkdir -p .github/assets/badges

          for module in semantic concurrency; do
            COV=$(go tool cover -func=coverage-files/coverage-${module}/coverage_package_${module}.out | grep total | awk '{print $3}')
            NUM=${COV%\%}
            if (( $(echo "$NUM >= 95" | bc -l) )); then
              COLOR="green"
            elif (( $(echo "$NUM >= 85" | bc -l) )); then
              COLOR="yellow"
            else
              COLOR="red"
            fi

            echo "{\"schemaVersion\":1,\"label\":\"$module\",\"message\":\"$COV\",\"color\":\"$COLOR\"}" \
              > .github/assets/badges/${module}.json
          done

      - name: Commit badges
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/assets/badges/*.json
          git commit -m "chore: update coverage badges [skip ci]" || echo "No changes"
          git push